### ISSUE TITLE
Lots of erroes when i did "catkin_make"

### ISSUE THREAD

**Issue by Joemeng-liu** [lisean789/innfos_gluon_ros#2]
CSignal.hpp:74:5: error: expected ‘)’ before ‘}’ token.
actuatorcontroller.h:907:11: error: expected nested-name-specifier before ‘doubleFuncPointer’
gluon_control_node.cpp:58:16: error: ‘class ros_control_boilerplate::GenericHWControlLoop’ has no member named ‘run’
There three files give me  errors and i have no idea with it, so i need someone who has made it to help me.

- [ ]

**Comment by lisean789** [comment]
are you using ros melodic?
I have updated the readme. Make sure you have installed all the dependencies before building.
Cheers!
